//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCo.Process.DeliveryNotificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryNotificationService.IDeliveryNotificationService")]
    public interface IDeliveryNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryNotificationService/NotifyDeliveryCompletion", ReplyAction="http://tempuri.org/IDeliveryNotificationService/NotifyDeliveryCompletionResponse")]
        void NotifyDeliveryCompletion(System.Guid pDeliveryId, DeliveryCo.Services.Interfaces.DeliveryInfoStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryNotificationService/NotifyDeliverySubmission", ReplyAction="http://tempuri.org/IDeliveryNotificationService/NotifyDeliverySubmissionResponse")]
        void NotifyDeliverySubmission(System.Guid orderNumber, System.Guid pDeliveryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeliveryNotificationServiceChannel : DeliveryCo.Process.DeliveryNotificationService.IDeliveryNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryNotificationServiceClient : System.ServiceModel.ClientBase<DeliveryCo.Process.DeliveryNotificationService.IDeliveryNotificationService>, DeliveryCo.Process.DeliveryNotificationService.IDeliveryNotificationService {
        
        public DeliveryNotificationServiceClient() {
        }
        
        public DeliveryNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NotifyDeliveryCompletion(System.Guid pDeliveryId, DeliveryCo.Services.Interfaces.DeliveryInfoStatus status) {
            base.Channel.NotifyDeliveryCompletion(pDeliveryId, status);
        }
        
        public void NotifyDeliverySubmission(System.Guid orderNumber, System.Guid pDeliveryId) {
            base.Channel.NotifyDeliverySubmission(orderNumber, pDeliveryId);
        }
    }
}
