//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Components.BankAsynchronousTransferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankAsynchronousTransferService.IBankAsynchronousTransferService")]
    public interface IBankAsynchronousTransferService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankAsynchronousTransferService/Transfer")]
        void Transfer(double pAmount, int pFromAcctNumber, int pToAcctNumber, string pDescription);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankAsynchronousTransferServiceChannel : VideoStore.Business.Components.BankAsynchronousTransferService.IBankAsynchronousTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankAsynchronousTransferServiceClient : System.ServiceModel.ClientBase<VideoStore.Business.Components.BankAsynchronousTransferService.IBankAsynchronousTransferService>, VideoStore.Business.Components.BankAsynchronousTransferService.IBankAsynchronousTransferService {
        
        public BankAsynchronousTransferServiceClient() {
        }
        
        public BankAsynchronousTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankAsynchronousTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAsynchronousTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAsynchronousTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Transfer(double pAmount, int pFromAcctNumber, int pToAcctNumber, string pDescription) {
            base.Channel.Transfer(pAmount, pFromAcctNumber, pToAcctNumber, pDescription);
        }
    }
}
