//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Components.BankSynchronousTransferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankSynchronousTransferService.IBankSynchronousTransferService")]
    public interface IBankSynchronousTransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSynchronousTransferService/Transfer", ReplyAction="http://tempuri.org/IBankSynchronousTransferService/TransferResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void Transfer(double pAmount, int pFromAcctNumber, int pToAcctNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankSynchronousTransferServiceChannel : VideoStore.Business.Components.BankSynchronousTransferService.IBankSynchronousTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankSynchronousTransferServiceClient : System.ServiceModel.ClientBase<VideoStore.Business.Components.BankSynchronousTransferService.IBankSynchronousTransferService>, VideoStore.Business.Components.BankSynchronousTransferService.IBankSynchronousTransferService {
        
        public BankSynchronousTransferServiceClient() {
        }
        
        public BankSynchronousTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankSynchronousTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankSynchronousTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankSynchronousTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Transfer(double pAmount, int pFromAcctNumber, int pToAcctNumber) {
            base.Channel.Transfer(pAmount, pFromAcctNumber, pToAcctNumber);
        }
    }
}
